apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 615115875849.dkr.ecr.us-east-1.amazonaws.com/frontend:latest
          env:
          - name: REACT_APP_MOVIE_API_URL
            value: http://a429ff6ca33604ffd804aab7ac995e02-1607427481.us-east-1.elb.amazonaws.com
          ports:
            - containerPort: 3000
